### ISSUE TITLE
Get your environment running

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/SOSWedding#3]
1. Setup [Android Studio](https://developer.android.com/studio) on your computer.
2. Setup repository in your studio
3. Run application
4. Play with code, hello world shenanigans
5. Once ready, go assign yourself a task!

**Comment by imabhijit** [comment]
Hi,
Can you invite me to the project?
Thanks.

**Comment by tarekait1996** [comment]
can we close this issue or is there anyone still who did not set up his android env?
